AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Subdomain:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String

Globals:
  Function:
    Handler: Provided
    Runtime: provided
    CodeUri: ./.build/lambda/SwiftSamApp/lambda.zip
    MemorySize: 256
    Timeout: 30
    Environment:
      Variables:
        LOG_LEVEL: DEBUG
    AutoPublishAlias: Live
    DeploymentPreference:
      Type: AllAtOnce

Resources:
  Cert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${Subdomain}.{DomainName}'
      DomainValidationOptions:
        - DomainName: !Sub '${Subdomain}.{DomainName}'
          HostedZoneId: !Ref 'HostedZoneId'
      ValidationMethod: DNS
        
  CnameRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub '${Subdomain}.{DomainName}'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !Sub '${Subdomain}.{DomainName}'
    DependsOn: Cert

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Sub '${Subdomain}.{DomainName}'
        CertificateArn: !Ref 'Cert'
        Route53:
          HostedZoneId: !Ref 'HostedZoneId'

  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Method: GET
            Path: /
  HelloLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Hello}"
      RetentionInDays: 1

Outputs:
  HelloApi:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/"
