AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for SwiftSamApp.Api

Globals:
  Function:
    Handler: Provided
    Runtime: provided
    CodeUri: ./.build/lambda/SwiftSamApp/lambda.zip
    MemorySize: 258
    Timeout: 30
    AutoPublishAlias: Live
    DeploymentPreference:
      Type: AllAtOnce

Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
  HelloLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Hello}"
      RetentionInDays: 1

Outputs:
  HelloApi:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessHttpApi.Stage}/"
