version: 0.2
phases:
  install:
    commands:
      # See https://swift.org/download/#using-downloads
      - >
        yum -y install
        binutils
        gcc
        git
        glibc-static
        gzip
        libbsd
        libcurl
        libedit
        libicu
        libsqlite
        libstdc++-static
        libuuid
        libxml2
        tar
        tzdata
      - wget -q --progress=bar:force:noscroll https://swift.org/builds/swift-5.2.5-release/amazonlinux2/swift-5.2.5-RELEASE/swift-5.2.5-RELEASE-amazonlinux2.tar.gz
      - tar xzf swift-5.2.5-RELEASE-amazonlinux2.tar.gz
      - ls swift-5.2.5-RELEASE-amazonlinux2
      - mv swift-5.2.5-RELEASE-amazonlinux2 /usr/bin/swift
      - export PATH=/usr/bin/swift:"${PATH}"
      - echo $PATH
  pre_build:
    commands:
      - echo "ProjectPath $ProjectPath"
      - echo "ArtifactBucket $ArtifactBucket"
      - echo "ArtifactBucketPrefix $ArtifactBucketPrefix"
      - echo "TemplateFileName $TemplateFileName"
      - echo "OutputTemplateFileName $OutputTemplateFileName"
      - cd $ProjectPath
      - swift --version
  build:
    commands:
      - swift build --product SwiftSamApp -c release
      # see https://github.com/swift-server/swift-aws-lambda-runtime/blob/master/Examples/LambdaFunctions/scripts/package.sh
      - exe_path = .build/release/SwiftSamApp
      - target_dir = .build/lambda/SwiftSamApp
      - mkdir -p "$target_dir"
      - cp "$exe_path" "$target_dir/"
      - ldd "$exe_path" | grep swift | awk '{print $3}' | xargs cp -Lv -t "$target_dir"
      - cd "$target_dir"
      - ln -s "SwiftSamApp" "bootstrap"
      - zip --symlinks lambda.zip *
      - >
        sam package
        --template-file $TemplateFileName
        --output-template-file $OutputTemplateFileName
        --s3-bucket $ArtifactBucket
        --s3-prefix $ArtifactBucketPrefix
        --force-upload
        --debug
artifacts:
  base-directory: $ProjectPath
  files:
    - $OutputTemplateFileName
