version: 0.2
phases:
  install:
    commands:
      # see https://www.swift.org/install/linux/tarball/ and https://www.swift.org/install/linux/amazonlinux/2/#versions
      - >
        yum -y install
        binutils
        gcc
        git
        glibc-static
        gzip
        libbsd
        libcurl
        libedit
        libicu
        libsqlite
        libstdc++-static
        libuuid
        libxml2
        tar
        tzdata
      # wget writes an obnoxious amount of progress lines, so turn that off
      - wget -q --progress=bar:force:noscroll https://download.swift.org/swift-6.0.3-release/amazonlinux2/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-amazonlinux2.tar.gz
      - wget -q --progress=bar:force:noscroll https://download.swift.org/swift-6.0.3-release/amazonlinux2/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-amazonlinux2.tar.gz.sig
      - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
      - gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift
      - gpg --verify swift-6.0.3-RELEASE-amazonlinux2.tar.gz.sig
      - tar xzf swift-6.0.3-RELEASE-amazonlinux2.tar.gz
      - pwd
      - ls -l
      - ls -l swift-6.0.3-RELEASE-amazonlinux2/usr/bin
      - export PATH=$(pwd)/swift-6.0.3-RELEASE-amazonlinux2/usr/bin:"${PATH}"
      - echo $PATH
      - which swift
  pre_build:
    commands:
      - echo "ProjectPath $ProjectPath"
      - echo "ArtifactBucket $ArtifactBucket"
      - echo "ArtifactBucketPrefix $ArtifactBucketPrefix"
      - echo "TemplateFileName $TemplateFileName"
      - echo "OutputTemplateFileName $OutputTemplateFileName"
  build:
    commands:
      - cd $ProjectPath
      - swift --version
      - swift package --version
      - swift build --product SwiftSamApp -c release
      # see https://github.com/swift-server/swift-aws-lambda-runtime/blob/master/Examples/LambdaFunctions/scripts/package.sh
      - export BuildDir=".build/release/SwiftSamApp"
      - export ZipDir=".build/lambda/SwiftSamApp"
      - mkdir -p "$ZipDir"
      - cp "$BuildDir" "$ZipDir/"
      - ldd "$BuildDir" | grep swift | awk '{print $3}' | xargs cp -Lv -t "$ZipDir"
      - cd "$ZipDir"
      - ln -s "SwiftSamApp" "bootstrap"
      - zip --symlinks lambda.zip *
      - cd ../../..
      - >
        sam package
        --template-file $TemplateFileName
        --output-template-file $OutputTemplateFileName
        --s3-bucket $ArtifactBucket
        --s3-prefix $ArtifactBucketPrefix
        --force-upload
        --debug
artifacts:
  base-directory: $ProjectPath
  files:
    - $OutputTemplateFileName
