version: 0.2
phases:
  install:
    commands:
       # See https://www.swift.org/install/linux/rpm/
      - curl https://download.swift.org/experimental-use-only/repo/amazonlinux/releases/2/swiftlang.repo > /etc/yum.repos.d/swiftlang.repo
      # see https://stackoverflow.com/questions/73056540/no-module-named-amazon-linux-extras-when-running-amazon-linux-extras-install-epe
      - PYTHON=python2 amazon-linux-extras install epel -y
      - yum install swiftlang -y
      - swift sdk install https://download.swift.org/swift-6.0-release/static-sdk/swift-6.0-RELEASE/swift-6.0-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 7984c2cf175bde52ba6ea1fcbe27fc4a148a6237c41c719209c9288ed3ceb652
      - echo $PATH
  pre_build:
    commands:
      - echo "ProjectPath $ProjectPath"
      - echo "ArtifactBucket $ArtifactBucket"
      - echo "ArtifactBucketPrefix $ArtifactBucketPrefix"
      - echo "TemplateFileName $TemplateFileName"
      - echo "OutputTemplateFileName $OutputTemplateFileName"
  build:
    commands:
      - cd $ProjectPath
      - swift --version
      - swift package --version
      - swift build --product SwiftSamApp -c release
      # see https://github.com/swift-server/swift-aws-lambda-runtime/blob/master/Examples/LambdaFunctions/scripts/package.sh
      - export BuildDir=".build/release/SwiftSamApp"
      - export ZipDir=".build/lambda/SwiftSamApp"
      - mkdir -p "$ZipDir"
      - cp "$BuildDir" "$ZipDir/"
      - ldd "$BuildDir" | grep swift | awk '{print $3}' | xargs cp -Lv -t "$ZipDir"
      - cd "$ZipDir"
      - ln -s "SwiftSamApp" "bootstrap"
      - zip --symlinks lambda.zip *
      - cd ../../..
      - >
        sam package
        --template-file $TemplateFileName
        --output-template-file $OutputTemplateFileName
        --s3-bucket $ArtifactBucket
        --s3-prefix $ArtifactBucketPrefix
        --force-upload
        --debug
artifacts:
  base-directory: $ProjectPath
  files:
    - $OutputTemplateFileName
